<?xml version="1.0"?>
<!-- Revolute-Revolute Manipulator -->
<robot name="rrbot" xmlns:xacro="http://www.ros.org/wiki/xacro">

  <!-- Constants for robot dimensions -->
   <xacro:property name="width" value="0.1" />   <!-- Beams are square in length and width -->
  <xacro:property name="height" value="0.5" />   <!-- Links -->
  <xacro:property name="axle_offset" value="0.00" /> <!-- Space between joint and end of beam -->
  <xacro:property name="damp" value="0.7" />    <!-- damping coefficient -->

  <!-- Default Inertial -->
  <xacro:macro name="default_inertial" params="z_value mass">
    <inertial>
      <origin xyz="0 0 ${z_value}" rpy="0 0 0"/>
      <mass value="${mass}" />
      <inertia ixx="0" ixy="0.0" ixz="0.0"
               iyy="0" iyz="0.0"
               izz="0" />
      </inertial>
  </xacro:macro>
<gazebo reference="mid_link">
  <material>Gazebo/Blue</material>
</gazebo>
<gazebo reference="link2">
  <material>Gazebo/Red</material>
</gazebo>
<gazebo reference="link1">
  <material>Gazebo/Green</material>
</gazebo>

   <!-- Top Link -->
  <link name="mid_link">
    <visual>
      <origin xyz="0 0 ${height/2 - axle_offset}" rpy="0 0 0"/>
      <geometry>
	<box size="${width} ${width} ${height}"/>
      </geometry>
    </visual>

    <collision>
      <origin xyz="0 0 ${height/2 - axle_offset}" rpy="0 0 0"/>
      <geometry>
	<box size="${width} ${width} ${height/1.5}"/>
      </geometry>
    </collision>

    <xacro:default_inertial z_value="${height/2 - axle_offset}" mass="1"/>
  </link>

  <!-- Top Link -->
  <link name="link1">
    <visual>
      <origin xyz="0 0 ${height/2 - axle_offset}" rpy="0 0 0"/>
      <geometry>
	<box size="${width} ${width} ${height}"/>
      </geometry>
    </visual>

    <collision>
      <origin xyz="0 0 ${height/2 - axle_offset}" rpy="0 0 0"/>
      <geometry>
	<box size="${width} ${width} ${height/1.5}"/>
      </geometry>
    </collision>

    <xacro:default_inertial z_value="${height/2 - axle_offset}" mass="1"/>
  </link>
 
  <!-- Joint between Middle Link and Top Link -->
  <joint name="joint_top" type="revolute">
    <parent link="mid_link"/>
    <child link="link1"/>
    <origin xyz="${width/2} ${width/2} ${height}" rpy="0 0 0"/>
    <axis xyz="0 1 0"/>
    <dynamics damping="${damp}"/>
    <limit effort="100.0" velocity="0.5" lower="-3.14" upper="3.14" />
  </joint>

</robot>
